source 'https://rubygems.org'
ruby '2.5.1'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sequel' # https://github.com/jeremyevans/sequel
gem 'foreman'
gem 'sqlite3'
gem 'pry'
gem 'mail'
gem 'listen'
gem 'dotenv'
gem 'bcrypt'
gem 'rubocop'
gem 'openssl'
gem 'rack-ssl-enforcer'
gem 'minitest'
gem 'rack-ssl'
gem 'thin'
gem 'jwt'
